import javax.swing.JFrame;

public class Calculator extends javax.swing.JPanel
{
	private static final long serialVersionUID = 1L;
	//private boolean done;
	private JFrame frame;
	/** Creates new form NewJPanel */
	public Calculator(JFrame fr)
	{
		frame = fr;	
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CurrentGrade = new javax.swing.JTextField();
        leave = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        WantGrade = new javax.swing.JTextField();
        worth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tips = new javax.swing.JTextArea();

        jLabel1.setText("Current Grade in Class: (Whole Numbers Only)");

        jLabel2.setText("Grade you want to have in Class: (Whole Numbers Only)");

        jLabel3.setText("Percent your Final Exam Grade is Worth: (Whole Numbers Only)");

        leave.setText("Leave");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	frame.dispose();
            	//done = true;
            	//done();
                leaveActionPerformed(evt);
            }
        });

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	int cg1 = Integer.parseInt(CurrentGrade.getText());
            	int wg1 = Integer.parseInt(WantGrade.getText());
            	int ew1 = Integer.parseInt(worth.getText());
            	double cg = cg1;
            	double wg = wg1;
            	double ew = ew1;
            	cg /= 100;
            	wg /= 100;
            	ew /= 100;
            	//System.out.println(cg + "" + wg + "" + ew);
            	double Ans = (((wg-((1.0-ew)*cg))/ew)*100);
            	Answer.setText(""+ (int) Math.round(Ans));
            	//System.out.println(Ans);
            	if(Ans<30)
            	{
            		Tips.setText("Why are you taking this exam?");
            	}
            	if(Ans>40)
            	{
            		Tips.setText("Either your grade is a bit too high,\nor your expectations are a bit too low. \nEither way, you're good.");
            	}
            	if(Ans>50)
            	{
            		Tips.setText("Tear the test up as soon as you recieve \nit into little pieces and eat them. \nThen play frisbee with a friend at the other \nside of the room. If anything happpens, \n blame it on the Sherman Anit-trust Act of 1890 \nor the lack of Omega-3 in Hippototamus milk.");
            	}
            	if(Ans>60)
            	{
            		Tips.setText("Rip up the test halfway through \nand ask the teacher for another copy.");
            	}
            	if(Ans>70)
            	{
            		Tips.setText("Don't even waste your time studying. \n(Battlefield 3 is free on Origin)");
            	}
            	if(Ans>80)
            	{
            		Tips.setText("Do the Scantron in crayon just to see what happens.");
            	}
            	if(Ans>90)
            	{
            		Tips.setText("You should crack open the textbook. As in now.");
            	}
            	if(Ans>100)
            	{
            		Tips.setText("You might want to aim a bit lower.");
            	}
            	if(Ans>110)
            	{
            		Tips.setText("McDonald's is always hiring.");
            	}
                calculateActionPerformed(evt);
            }
        });

        jLabel4.setText("You need this Percent on the Final Exam:");

        jLabel5.setText("Tips from Albert:");

        Tips.setColumns(20);
        Tips.setRows(5);
        jScrollPane1.setViewportView(Tips);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CurrentGrade)
                            .addComponent(WantGrade)
                            .addComponent(worth, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(leave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WantGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(worth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void leaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_leaveActionPerformed
	{//GEN-HEADEREND:event_leaveActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_leaveActionPerformed

	private void calculateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_calculateActionPerformed
	{//GEN-HEADEREND:event_calculateActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_calculateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JTextField CurrentGrade;
    private javax.swing.JTextArea Tips;
    private javax.swing.JTextField WantGrade;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leave;
    private javax.swing.JTextField worth;
    // End of variables declaration//GEN-END:variables

	/* public boolean done()
	{
		return done;
	}*/
}